//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rencontre
    {
        public string NomGagnant { get; set; }
        public string NomPerdant { get; set; }
        public string NomTournoi { get; set; }
        public System.DateTime DateTournoi { get; set; }
        public string Score { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Joueur Joueur1 { get; set; }
        public virtual Tournoi Tournoi { get; set; }
    }
}
